name: DEV - Build

on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  APP_NAME: kanjan-tutorial-frontend
  CONTAINER_REPOSITORY: "acrkanjantutorial001.azurecr.io"
  IMAGE_TAG: "0.0.1-SNAPSHOT"     

jobs:
  unitest:
    name: UnitTest
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.6' # The Go version to download (if necessary) and use.


    - name: Install dependencies
      run: |
        go env -w GO111MODULE=on
        go get -u github.com/gin-gonic/gin
        go get -u go.mongodb.org/mongo-driver/mongo
        go get -u github.com/stretchr/testify
        go mod vendor

    - name: Unit test
      run: |
        go test -coverprofile coverage.out ./...
        go tool cover -html coverage.out -o report.html
        
    - name: Upload Reports
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results
        path: '${{ github.workspace }}/report.html'